# Model to evaluate
model:
  load_from: "distilgpt2"
  torch_dtype: "bfloat16"

# Settings specific to lm_harness.evaluate
evaluator:
  tasks: ["hellaswag"]
  num_fewshot: 5
  limit: 10

quantization:
  load_in_4bit: True
  bnb_4bit_quant_type: "fp4"

# Tracking info for where to log the run results
tracking:
  name: "lm-buddy-lm-harness"
  project: "lm-buddy-examples"
  entity: "mozilla-ai"
