# Model to evaluate, specified as a W&B artifact
model:
  base_url: "1.2.3.4:8000/v1/completions"
  model_backend: "mistralai/Mistral-7B-v0.1"

# Settings specific to lm_harness.evaluate
evaluator:
  tasks: ["gsm8k"]
  num_fewshot: 5
  limit: 10

tracking:
  name: "flamingo-example-lm-harness-inference"
  project: "flamingo-examples"
  entity: "mozilla-ai"

ray:
  num_cpus: 1
  timeout: 3600
