name: Required Status Checks

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Environment
        id: setup
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV
        continue-on-error: false

      - name: Install Dependencies
        id: install_dependencies
        run: |
          . .venv/bin/activate
          uv pip install toml-cli
          uv pip install $(toml get --toml-path pyproject.toml "project.optional-dependencies.ruff[0]")
        continue-on-error: false
          
      - name: Linting with Ruff
        id: ruff
        run: |
          . .venv/bin/activate
          ruff --output-format=github check .
        continue-on-error: false

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Environment
        id: setup
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV
        continue-on-error: false

      - name: Install Package
        id: install_package
        run: |
          . .venv/bin/activate
          uv pip install "lm_buddy[dev] @ ."
        continue-on-error: false

      - name: Unit Tests
        id: unit_tests
        run: |
          . .venv/bin/activate
          pytest tests/unit
        continue-on-error: false

      - name: Integration Tests
        id: integration_tests
        run: |
          . .venv/bin/activate
          pytest tests/integration
        continue-on-error: false
