name: Code Style

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: pipx install ruff==0.2.1 # Needs to match pyproject.toml

      - name: Lint with Ruff
        run: ruff --output-format=github .
        continue-on-error: false
