name: Tests

on:
  push:
    branches:
      - "main"
    paths:
    - "src/**"
  pull_request:
    branches:
      - "**"
    paths:
    - "src/**"

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Lock Poetry
        run: poetry lock

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install package
        run: poetry install
        continue-on-error: true

      - name: Run unit tests
        run: |
          poetry run pytest tests/unit
        continue-on-error: false

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Lock Poetry
        run: poetry lock

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install package
        run: poetry install
        continue-on-error: true

      - name: Run integration tests
        run: |
          poetry run pytest tests/integration
        continue-on-error: false
